DROP DATABASE IF EXISTS venturi;
CREATE DATABASE IF NOT EXISTS venturi;
USE venturi;

-- Table Users

CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user VARCHAR(30) UNIQUE NOT NULL,
	name VARCHAR(45) NOT NULL,
    surname VARCHAR(45) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	biography VARCHAR(255),
	created_at TIMESTAMP NOT NULL ,
	PRIMARY KEY (id)

)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS posts(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	content VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	user_id INT UNSIGNED NOT NULL,

	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION ON UPDATE CASCADE,

	PRIMARY KEY (id)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS comments(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	content VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	post_id INT UNSIGNED NOT NULL,
	user_id INT UNSIGNED NOT NULL,

	FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION ON UPDATE CASCADE,

	PRIMARY KEY (id)
)ENGINE = InnoDB;