DROP DATABASE IF EXISTS venturi;
CREATE DATABASE IF NOT EXISTS venturi;
USE venturi;

-- Table Users

CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user VARCHAR(20) NOT NULL,
	name VARCHAR(45) NOT NULL,
    surname VARCHAR(60) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL ,
	PRIMARY KEY (id)

)ENGINE = InnoDB;
